// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import {
  Address,
  DataSourceTemplate,
  DataSourceContext,
} from "@graphprotocol/graph-ts";

export class WeightedPool extends DataSourceTemplate {
  static create(address: Address): void {
    DataSourceTemplate.create("WeightedPool", [address.toHex()]);
  }

  static createWithContext(address: Address, context: DataSourceContext): void {
    DataSourceTemplate.createWithContext(
      "WeightedPool",
      [address.toHex()],
      context,
    );
  }
}

export class WeightedPoolV2 extends DataSourceTemplate {
  static create(address: Address): void {
    DataSourceTemplate.create("WeightedPoolV2", [address.toHex()]);
  }

  static createWithContext(address: Address, context: DataSourceContext): void {
    DataSourceTemplate.createWithContext(
      "WeightedPoolV2",
      [address.toHex()],
      context,
    );
  }
}

export class WeightedPool2Tokens extends DataSourceTemplate {
  static create(address: Address): void {
    DataSourceTemplate.create("WeightedPool2Tokens", [address.toHex()]);
  }

  static createWithContext(address: Address, context: DataSourceContext): void {
    DataSourceTemplate.createWithContext(
      "WeightedPool2Tokens",
      [address.toHex()],
      context,
    );
  }
}

export class ManagedPool extends DataSourceTemplate {
  static create(address: Address): void {
    DataSourceTemplate.create("ManagedPool", [address.toHex()]);
  }

  static createWithContext(address: Address, context: DataSourceContext): void {
    DataSourceTemplate.createWithContext(
      "ManagedPool",
      [address.toHex()],
      context,
    );
  }
}

export class OffchainAggregator extends DataSourceTemplate {
  static create(address: Address): void {
    DataSourceTemplate.create("OffchainAggregator", [address.toHex()]);
  }

  static createWithContext(address: Address, context: DataSourceContext): void {
    DataSourceTemplate.createWithContext(
      "OffchainAggregator",
      [address.toHex()],
      context,
    );
  }
}
